carbon_dating/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from author.views import home_view, explore_view
from author import views as author_views
# from authentication.views import SignUpView
from authentication import views as authentication_views
from direct_messages.urls import url_patterns as messages_urls
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', author_views.home_view, name='homepage'),
    # path('', include('django.contrib.auth.urls')),
    path('login/', authentication_views.LoginFormView.as_view(), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(), name="logout"),
    path('explore/', author_views.explore_view, name="explore"),
    path('signup/', authentication_views.SignUpView.as_view(), name='signup'),
    path('posts/', include('post.urls')),
    path('posts/', include('comment.urls')),
    path(
        'author_profile/<int:user_id>/',
        author_views.author_profile,
        name="author_profile"
        ),
    path('admire/<int:user_id>/', author_views.admire_view),
    path('profile_admire/<int:user_id>/', author_views.profile_admire_view),
    path('change_profile/', author_views.change_profile, name="change_profile"),
    path('password/', author_views.PasswordsChangeView.as_view(template_name="change_password.html")),
    path('tz_detect/', include('tz_detect.urls')),
    *messages_urls,
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post import views


urlpatterns = [
    path("post/<int:id>/", views.post_detail, name="post_detail"),
    path("new_post/", views.new_post, name="new_post"),
    path("post/<int:pk>/remove/", views.DeletePost.as_view(), name="delete_post")
]

author/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField
from django.utils import timezone
# Create your models here.


class Author(AbstractUser):
    ROCK_CHOICES = (
        ('IGNEOUS', 'Igneous'),
        ('SEDIMENTARY', 'Sedimentary'),
        ('METAMORPHIC', 'Metamorphic')
    )
    rock_type = models.CharField(
        max_length=50, choices=ROCK_CHOICES, null=True)
    interested_in = MultiSelectField(
        max_length=35,
        choices=ROCK_CHOICES,
        null=True
    )
    admirers = models.ManyToManyField(
        'self', symmetrical=False, blank=True, related_name='admiring')
    bio = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    birthday = models.DateField(null=True)
    profilepic = models.ImageField(
        upload_to='users/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.username

post/models.py
from django.db import models
from django.utils import timezone
from author.models import Author


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    caption = models.CharField(max_length=140, default='')
    image = models.ImageField(
        upload_to="images/",
        height_field=None,
        width_field=None,
        max_length=None
        )
    timestamp = models.DateTimeField(default=timezone.now)

author/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User



class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':":form-control", 'type':'password'}))
    new_password1 = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'class':":form-control", 'type':'password'}))
    new_password2 = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'class':":form-control", 'type':'password'}))

    class Meta:
        model = User
        fields = (
            'old_password',
            'new_password1',
            'new_password2'
        )

templates/author_detail.html
{% extends 'base.html' %}

{% block content %}
<html>
<head>
  <title>{{author_info.username}}'s Profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <style>
  .img {
    height: 200px;
    width: 200px;
  }
a, a:hover, a:focus, a:active {
    text-decoration: none;
    color: inherit;
    cursor:pointer;
}
    
  
  </style>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h2>{{author_info.username}}</h2>
      <div><img class="img" src="{{author_info.profilepic.url}}"></div>
      <p>{{author_info.bio}}</p>
      {% if author_info.id != request.user.id  %}


    {% if author_info not in request.user.admirers.all %}
       <a href="/profile_admire/{{author_info.id}}"><button type="button" class="btn btn-outline-danger btn-sm"> Admire</a> <i class="fa fa-heart"></i></button></a>
        
        {% else %}
         <a href="/profile_admire/{{author_info.id}}"><button type="button" class="btn btn-outline-secondary btn-sm"> Unadmire <i class="fa fa-frown-o"></i></button></a>
         
    {% endif %}

{% endif %} 
    {% if author_info.id == request.user.id %}
    <a href="/change_profile/"><button>Update Profile</button></a>
    {% endif %}    
      <h5>{{author_info.rock_type}}</h5>  
      <p>{{author_info.interested_in}}</p>
      <p>Member since {{author_info.created_at}} </p>
      <hr class="hidden-sm hidden-md hidden-lg">
    </div>
    <div class="col-sm-8">
      <h2>Recent Posts</h2>
      
      {% for p in posts %}
      <h5>{{p.caption}}, {{p.created_at}}</h5>
      <div ><img class="img"src="{{p.image.url}}"></div>
      <br>
      {% endfor %}
  </div>
</div>


</body>

{% comment %} <p>
    <img src="{{author_info.profilepic.url}}">
    {{author_info}}
    {{author_info.rock_type}}
    {{author_info.interested_in}}
    {{author_info.bio}}
    {{author_info.created_at}}
    {% for p in post %}
        {{p.caption}}
    {% endfor %}
</p>
{% if author_info.id != request.user.id  %}

<a href="/profile_admire/{{author_info.id}}"><button>
    {% if author_info not in request.user.admirers.all %}
        Admire
        {% else %}
        Unadmire
    {% endif %}
</button></a>

{% endif %} {% endcomment %}

</html>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <meta charset="utf-8">
</head>
{% load tz_detect %}
{% tz_detect %}
<body>
<header>
            {% include 'navbar.html' %}

        </header>
            
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<html>
<title>Change Password</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" class="fa" type="text/css" href="{% static 'css/login.css' %}">
<body>
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <img class="logo" src="{% static 'media/logo-cyan.png' %}">
                </div>
                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form method="post">
                        {% csrf_token %}
                            <div class="form-group">
                                <label class="form-control-label">OLD PASSWORD</label>
                                <input type="password" class="form-control" name="old_password" id="id_old_password" required autofocus>
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">NEW PASSWORD (Password must contain at least 8 characters and can’t be entirely numeric.)</label>
                                <input type="password" class="form-control" name="new_password1" id="id_new_password1" required >
                            </div>
                               <div class="form-group">
                                <label class="form-control-label">NEW PASSWORD CONFIRMATION (Enter the same password as before, for verification.)</label>
                                <input type="password" class="form-control" name="new_password2" id="id_new_password2" required>
                            </div>
 
                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text" style="color: red;">
                                    {{form.errors}}
                                 </div>
                                <div class="col-lg-6 login-btm login-button signup-button">
                                    <button class="btn btn-outline-danger">CHANGE PASSWORD&nbsp; <i class="fa fa-key"></i></button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
</body>
</html>

{% endblock %}

templates/explore.html
{% extends 'base.html' %}
{% include navbar %}

{% load static %}

{% block content %}



{% if user.is_authenticated %}
<title>Explore</title>

<link rel="stylesheet" type="text/css" href="{% static 'css/explore.css' %}">

<div class="wrapper">
  <section class="columns">
    <div class="column left border-end border-secondary">
      <h1 class="display-3" style="text-align:center;"><u>{{user.username}}</u></h1>
      <img class="avatar" alt="avatar" src="{{user.profilepic.url}}">
    </div>

    <div class="column border-end border-secondary" style="min-height: min-content;" >
    <h1 class="display-3" style="text-align:center;"><u>Potential Matches</u></h1>
      
      {% for user in users %}
      {% if user not in request.user.admirers.all%}
      <div class="card" style="text-align:center;width:250px;margin-left:150px;;margin-bottom:50px">
  <img class="card-img-top" src="{{user.profilepic.url}}" alt="potential match" style="height:200px">
  <div class="card-body">
    <h5 class="card-title">{{user.username}}</h5>

   <button type="button" class="btn btn-outline-danger btn-sm"><a href="/admire/{{user.id}}/">Admire</a> <i class="fa fa-heart"></i></button>
        
      
    <button type="button" class="btn btn-outline-success btn-sm"><a href="/author_profile/{{user.id}}">Profile</a> <i class="fa fa-user"></i></button>
    
  </div>
</div>
        
        {% endif %}
        {% endfor %}
      
        
    </div>
    

    <div class="column">
     <h1 class="display-3" style="text-align:center;"><u>Recent Matches</u></h1>
     {% for u in user.admirers.all %}
        <div class="recent-matches">
        
        <p class="h4" style="text-align:center;"><u>{{u.username}}</u></p>
        <br>
        <a href="/author_profile/{{u.id}}"><img class="avatar" alt="avatar" src="{{u.profilepic.url}}"></a>
        
        </div>
     {% endfor %}
    </div>
      
  </section> 



  
  
  
  
  {% comment %} Hi {{ user.username }}!
  

  <img src="{{user.profilepic.url}}" width="100px" height="100px"> {% endcomment %}
{% endif %}
    {% endblock %}

templates/home.html
{% extends 'base.html' %}
{% include navbar %}

{% load static %}

{% block title %}Home{% endblock %}
{% block content %}



{% if user.is_authenticated %}
<title>{{user.username}}'s Homepage</title>

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

<div class="wrapper">
  <section class="columns">
    <div class="column left border-end border-secondary">
      <h1 class="display-3" style="text-align:center;"><u>{{user.username}}</u></h1>
      <img class="avatar" alt="avatar" src="{{user.profilepic.url}}">
      
      <div class="button-list">
      <button type="button" class="btn btn-outline-dark btn-lg"><a href="/explore/">Explore <i class="fa fa-arrow-right" aria-hidden="true"></i></a></button>
      </div>
      <!-- <div class="button-list">
      <button type="button" class="btn btn-outline-dark btn-lg">Chats <i class="fa fa-arrow-right" aria-hidden="true"></i></button>
      
      </div> -->
    </div>

    <div class="column border-end border-secondary" style="min-height: min-content;" >
      <h1 class="display-3" style="text-align:center;"><u>Recent Posts</u></h1>
      {% for u in user.admirers.all %}
      {% for post in u.post_set.all %}
      
     <a href="/posts/post/{{post.id}}/"><img src="{{post.image.url}}" alt="posts" class="img-thumbnail post-img"></a>
      
      {% endfor %}
      {% endfor %}

    </div>

    <div class="column">
      <h1 class="display-3" style="text-align:center;">
        <u>Recent Admirers</u>
      </h1>
      <div>
     {% for r in recent %}
     <br>
     
    <a href="/author_profile/{{r.admiring.id}}/"><img alt="Profile Pic" class="rounded-circle avi-small" src="{{r.admiring.profilepic.url}}"></a>
    <h2 class="recent-text">{{r.admiring.username}} is now admiring you!</h2>
  </div>
   
     {% endfor %}
    </div>
  </section>  



  
  
  
  
  {% comment %} Hi {{ user.username }}!
  

  <img src="{{user.profilepic.url}}" width="100px" height="100px"> {% endcomment %}
{% else %}
<h1>Not signed in</h1>
<a href="accounts/login/">Log in</a>
{% endif %}

    {% endblock %}

templates/navbar.html
{% load static %}
{% load filters %}
<link rel="stylesheet"  type="text/css" href="{% static 'css/navbar.css' %}">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="{% static 'media/logo-cyan.png' %}" alt="logo" width="150" height="30" class="d-inline-block align-text-top"></a>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/author_profile/{{request.user.id}}">Profile</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/posts/new_post">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/messages">Messages {% if request|unread_count != 0 %}({{request|unread_count}}){% endif %}</a>
        </li>
        <li class="nav-item"><button type="button" class="btn btn-outline-primary logout-button"><a href="{% url 'logout' %}">Logout</a></button></li>
      </ul>
    </div>
  </div>
</nav>

templates/update_profile.html
{% load static %}


{% block content %}
<html>
<title>Update {{request.user.username}}'s Profile</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" class="fa" type="text/css" href="{% static 'css/login.css' %}">
<body>
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    UPDATE PROFILE INFORMATION
                </div>
                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                        <label class="form-control-label">YOU CAN CHANGE YOUR PASSWORD BY USING THE BUTTON BELOW</label>
                        <br>
                        <br>
                        <button class="btn btn-outline-danger"><a href="../password/">CHANGE PASSWORD&nbsp; </a><i class="fa fa-key"></i></button>
                        </div>
                        <div class="form-group">
                            <label for="id_rock_type" class="form-control-label">ROCK TYPE</label>
                            <select class="form-select" name="rock_type" required id="id_rock_type">
                                <option value="IGNEOUS">Igneous</option>
                                <option value="SEDIMENTARY">Sedimentary</option>
                                <option value="METAMORPHIC">Metamorphic</option>
                            </select>
                            </div>
                            <div>
                            <label class="form-control-label">INTERESTED IN</label>
                            <div class="form-group" id="id_interested_in">
                            <div class="form-check" >
                            <input class="form-check-input" type="checkbox" name="interested_in"  value="IGNEOUS" id="id_interested_in_0">
                            <label class="form-check-label" for="id_interested_in_0">
                                Igneous
                            </label>
                            </div>
                             <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="interested_in"  value="SEDIMENTARY" id="id_interested_in_1">
                            <label class="form-check-label" for="id_interested_in_1">
                                Sedimentary
                            </label>
                            </div>
                             <div class="form-check">
                                  <input class="form-check-input" type="checkbox" name="interested_in"  value="METAMORPHIC" id="id_interested_in_2">
                            <label class="form-check-label" for="id_interested_in_2">
                                Metamorphic
                            </label>
                            </div>
                            </div>
                             <div class="form-group">
                                <label class="form-control-label">BIO</label>
                                <textarea name="bio" type="text" class="form-control" id="id_bio"></textarea>
                            </div>
                             <div class="form-group">
                                <label class="form-control-label">BIRTHDAY (Format: YYYY-MM-DD)</label>
                                <input type="text" class="form-control" name="birthday" id="id_birthday">
                            </div>
                            <div class="form-group">
                             <label class="form-control-label">PROFILE PICTURE</label>
                                <input type="file" class="form-control" name="profilepic" accept="image/" id="id_profilepic">
                            <div>
                            



                            </div>
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-button">
                                
                                    <button type="submit" class="btn btn-outline-primary">UPDATE PROFILE</button>
                                </div>
                               
                                 
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
</body>
</html>
{% endblock %} 